<a href="https://colab.research.google.com/github/Juxtpawan/AIML/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import math

In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5
print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)


tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [ ]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)
print(rand)
print(doubled)


tensor([[0.5582, 0.7723, 0.3881, 0.0103],
        [0.9352, 0.9311, 0.5909, 0.5563]])
tensor([[1.1164, 1.5446, 0.7762, 0.0205],
        [1.8705, 1.8622, 1.1817, 1.1126]])


In [ ]:
a = torch.ones(4, 3, 2)
b = a * torch.rand( 3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)
c = a * torch.rand( 3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)
d = a * torch.rand( 1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.9997, 0.0305],
         [0.3151, 0.0116],
         [0.2907, 0.6922]],

        [[0.9997, 0.0305],
         [0.3151, 0.0116],
         [0.2907, 0.6922]],

        [[0.9997, 0.0305],
         [0.3151, 0.0116],
         [0.2907, 0.6922]],

        [[0.9997, 0.0305],
         [0.3151, 0.0116],
         [0.2907, 0.6922]]])
tensor([[[0.6123, 0.6123],
         [0.9312, 0.9312],
         [0.9434, 0.9434]],

        [[0.6123, 0.6123],
         [0.9312, 0.9312],
         [0.9434, 0.9434]],

        [[0.6123, 0.6123],
         [0.9312, 0.9312],
         [0.9434, 0.9434]],

        [[0.6123, 0.6123],
         [0.9312, 0.9312],
         [0.9434, 0.9434]]])
tensor([[[0.3122, 0.0284],
         [0.3122, 0.0284],
         [0.3122, 0.0284]],

        [[0.3122, 0.0284],
         [0.3122, 0.0284],
         [0.3122, 0.0284]],

        [[0.3122, 0.0284],
         [0.3122, 0.0284],
         [0.3122, 0.0284]],

        [[0.3122, 0.0284],
         [0.3122, 0.0284],
         [0.3122, 0.0284]]])


In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))
# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)
# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))
# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2) # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool
# reductions:
print('\nReduction ops:')
print(torch.max(d)) # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d)) # average
print(torch.std(d)) # standard deviation
print(torch.prod(d)) # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.]) # x unit vector
v2 = torch.tensor([0., 1., 0.]) # y unit vector
m1 = torch.rand(2, 2) # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix
print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3) # 3 times m1
print(torch.svd(m3)) # singular value decomposition


Common functions:
tensor([[0.9237, 0.8300, 0.2510, 0.2036],
        [0.6844, 0.6438, 0.5357, 0.5491]])
tensor([[-0., 1., -0., -0.],
        [1., -0., -0., -0.]])
tensor([[-1.,  0., -1., -1.],
        [ 0., -1., -1., -1.]])
tensor([[-0.5000,  0.5000, -0.2510, -0.2036],
        [ 0.5000, -0.5000, -0.5000, -0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9299, 0.6980],
        [0.9759, 0.5713]])
tensor([[2.7898, 2.0939],
        [2.9276, 1.7138]])
torch.return_types.svd(
U=tensor([[-0.7169, -0.6971],
        [-0.6971,  0.7169]]),
S=tensor([4.8578, 0.2777]),
V=tensor([[-0.8319,  0.5550],
        [-0.5550, -0.8319]]))


/tmp/ipython-input-1338975324.py:40: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)


In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a)) # this operation creates a new tensor in memory
print(a) # a has not changed
b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b)) # note the underscore
print(b) # b has changed


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)
print(c)
d = torch.matmul(a, b, out=c)
print(c) # contents of c have changed
assert c is d # test c & d are same object, not just containing equal values
assert id(c) == old_id # make sure that our new c is the same object as the old one
torch.rand(2, 2, out=c) # works for creation too!
print(c) # c has changed again
assert id(c) == old_id # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[1.1881, 0.7843],
        [1.3656, 0.8191]])
tensor([[0.3588, 0.1373],
        [0.3723, 0.4895]])


In [ ]:
a = torch.ones(2, 2)
b = a
a[0][1] = 561 # we change a...
print(b) # ...and b is also altered


tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[  1., 561.],
        [  1.,   1.]])


In [ ]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)
b = a.clone()
print(b)
c = a.detach().clone()
print(c)
print(a)


tensor([[0.8059, 0.5624],
        [0.2211, 0.1718]], requires_grad=True)
tensor([[0.8059, 0.5624],
        [0.2211, 0.1718]], grad_fn=<CloneBackward0>)
tensor([[0.8059, 0.5624],
        [0.2211, 0.1718]])
tensor([[0.8059, 0.5624],
        [0.2211, 0.1718]], requires_grad=True)
